#ifndef LED_SEGMENTS_CONFIG_H
#define LED_SEGMENTS_CONFIG_H

#define FASTLED_USE_PROGMEM 1
#define IS_PROD false
#define LED_PIN 9

#define TRANSITION_DURATION_IN_MILLIS 1000
#define FPS 60
#define REFRESH_RATE_IN_MILLIS (1000 / FPS)
#define EFFECT_DURATION_IN_SECONDS 3

#define TRANSITION_DURATION_IN_MILLIS 1000
#define TRANSITION_DURATION_IN_FRAMES TRANSITION_DURATION_IN_MILLIS / REFRESH_RATE_IN_MILLIS
#define DISABLE_FADING true

#define DISPLAY_TYPE_TEST 1
#define DISPLAY_TYPE_FIBONACCI 2
#define DISPLAY_TYPE_DLH 3

#define DISPLAY_TYPE DISPLAY_TYPE_TEST

#if DISPLAY_TYPE == DISPLAY_TYPE_FIBONACCI
#include "displays/FibonacciDisplay.h"
#elif DISPLAY_TYPE == DISPLAY_TYPE_DLH
#include "displays/DlhDisplay.h"
#else
#include "displays/TestDisplay.h"
#endif

#endif //LED_SEGMENTS_CONFIG_H
